# Generated by Django 5.1 on 2026-09-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_cbaircraftmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbaircraftmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/bookmarks/aircraft/', verbose_name='기종 이미지'),
        ),
    ]
