# Generated by Django 5.1 on 2026-09-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0004_alter_cbaircraftmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
