# Generated by Django 5.1 on 2026-09-14 05:09

from django.db import migrations, models


def merge_duplicate_aircraft_models(apps, schema_editor):
    CBAircraftModel = apps.get_model('bookmarks', 'CBAircraftModel')
    codes = (
        CBAircraftModel.objects.order_by()
        .values_list('code', flat=True)
        .distinct()
    )

    for code in codes:
        aircraft = list(
            CBAircraftModel.objects.filter(code=code).order_by('id')
        )
        if len(aircraft) < 2:
            continue

        keeper = next((item for item in aircraft if item.image), aircraft[0])
        (
            CBAircraftModel.objects.filter(code=code)
            .exclude(pk=keeper.pk)
            .delete()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_cbtemplate_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbaircraftmodel',
            options={'ordering': ['code'], 'verbose_name': 'C/B Aircraft Model', 'verbose_name_plural': 'C/B Aircraft Models'},
        ),
        migrations.RemoveConstraint(
            model_name='cbaircraftmodel',
            name='unique_cb_aircraft_model_per_site',
        ),
        migrations.RemoveField(
            model_name='cbaircraftmodel',
            name='site',
        ),
        migrations.RunPython(
            merge_duplicate_aircraft_models,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='cbaircraftmodel',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='기종'),
        ),
    ]
