# Generated by Django 5.1 on 2026-09-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_alter_cbaircraftmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cbtemplate',
            name='unique_cb_template_per_site',
        ),
        migrations.RemoveField(
            model_name='cbtemplate',
            name='site',
        ),
        migrations.AddConstraint(
            model_name='cbtemplate',
            constraint=models.UniqueConstraint(fields=('aircraft_model', 'name'), name='unique_cb_template_per_aircraft'),
        ),
    ]
