# Generated by Django 5.1 on 2026-02-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manhour", "0009_alter_worksession_site"),
        ("manhour", "0009_taskmaster_site"),
    ]

    operations = []
