# Generated by Django 5.1 on 2026-03-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manhour', '0020_appsetting'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gibunpriority',
            new_name='manhour_gib_session_e6338f_idx',
            old_name='manning_gib_session_3525d4_idx',
        ),
    ]
