# Generated by Django 5.1 on 2026-03-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhour', '0025_workplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='site',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='defaultworkerdirectory',
            name='site',
            field=models.CharField(max_length=20, verbose_name='근무지'),
        ),
        migrations.AlterField(
            model_name='featuredvideo',
            name='site',
            field=models.CharField(blank=True, default='', help_text='Blank = all sites', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskmaster',
            name='site',
            field=models.CharField(max_length=20, verbose_name='근무지'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='site',
            field=models.CharField(max_length=20, verbose_name='근무지'),
        ),
    ]
