# Generated by Django 5.1 on 2026-04-14 00:00

from django.db import migrations, models


DEFAULT_KEY_BY_CODE = {
    "ICN-1그룹": "icn_group_1",
    "ICN-2그룹": "icn_group_2",
    "ICN-3그룹": "icn_group_3",
    "GMP-1그룹": "gmp_group_1",
    "GMP-2그룹": "gmp_group_2",
    "GMP-3그룹": "gmp_group_3",
}


def seed_workplace_config_keys(apps, schema_editor):
    Workplace = apps.get_model("manhour", "Workplace")
    for workplace in Workplace.objects.all():
        config_key = DEFAULT_KEY_BY_CODE.get(workplace.code)
        if not config_key:
            continue
        workplace.config_key = config_key
        workplace.save(update_fields=["config_key"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("manhour", "0028_appsetting_text_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplace",
            name="config_key",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="appsetting",
            name="site",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="defaultworkerdirectory",
            name="site",
            field=models.CharField(max_length=50, verbose_name="근무지"),
        ),
        migrations.AlterField(
            model_name="featuredvideo",
            name="site",
            field=models.CharField(
                blank=True, default="", help_text="Blank = all sites", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="taskmaster",
            name="site",
            field=models.CharField(max_length=50, verbose_name="근무지"),
        ),
        migrations.AlterField(
            model_name="workplace",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="workplace",
            name="label",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="worksession",
            name="site",
            field=models.CharField(max_length=50, verbose_name="근무지"),
        ),
        migrations.RunPython(seed_workplace_config_keys, noop_reverse),
    ]
