# Generated by Django 5.1 on 2026-01-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gibun_code', models.CharField(max_length=50, verbose_name='기번')),
                ('work_order', models.CharField(max_length=100)),
                ('op', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('default_mh', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='세션 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shift_type', models.CharField(choices=[('DAY', '주간 (08:00 ~ 20:00)'), ('NIGHT', '야간 (20:00 ~ 익일 08:00)')], default='DAY', max_length=10, verbose_name='근무 형태')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='기종')),
                ('gibun_input', models.CharField(blank=True, max_length=50, null=True)),
                ('work_order', models.CharField(blank=True, default='', max_length=100)),
                ('op', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('work_mh', models.FloatField(default=0.0)),
                ('is_manual', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('task_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manning.taskmaster')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manning.worksession')),
            ],
            options={
                'ordering': ['gibun_input', 'ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('limit_mh', models.FloatField(default=9.0)),
                ('used_mh', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manning.worksession')),
            ],
            options={
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_mh', models.FloatField(default=0.0)),
                ('start_min', models.IntegerField(blank=True, null=True)),
                ('end_min', models.IntegerField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='manning.worker')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='manning.workitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_min__isnull', True), ('start_min__isnull', True)), fields=('work_item', 'worker'), name='uniq_assignment_only_when_no_time')],
            },
        ),
        migrations.CreateModel(
            name='GibunTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gibun', models.CharField(max_length=50)),
                ('workers', models.ManyToManyField(blank=True, related_name='gibun_teams', to='manning.worker')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gibun_teams', to='manning.worksession')),
            ],
            options={
                'unique_together': {('session', 'gibun')},
            },
        ),
        migrations.CreateModel(
            name='GibunPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gibun', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=999)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manning.worksession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'order'], name='manning_gib_session_3525d4_idx')],
                'unique_together': {('session', 'gibun')},
            },
        ),
    ]
