# Generated by Django 6.0.1 on 2026-01-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gibun_code', models.CharField(max_length=50, unique=True, verbose_name='기번')),
                ('work_order', models.CharField(max_length=100)),
                ('op', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('default_mh', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='세션 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gibun_input', models.CharField(blank=True, max_length=50)),
                ('work_order', models.CharField(max_length=100)),
                ('op', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('work_mh', models.FloatField(default=0.0)),
                ('task_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manning.taskmaster')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manning.worksession')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('limit_mh', models.FloatField(default=9.0)),
                ('used_mh', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manning.worksession')),
            ],
        ),
    ]
