# Generated by Django 6.0.1 on 2026-01-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='gibun_code',
            field=models.CharField(max_length=50, verbose_name='기번'),
        ),
    ]
