# Generated by Django 5.1 on 2026-01-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['id']},
        ),
    ]
