# Generated by Django 5.1 on 2026-01-30 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0002_alter_worker_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('youtube_url', models.URLField(max_length=500, verbose_name='YouTube URL')),
                ('video_id', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Video ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
