# Generated by Django 6.0.1 on 2026-01-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0002_alter_taskmaster_gibun_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_mh', models.FloatField(default=0.0)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='manning.workitem')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='manning.worker')),
            ],
        ),
    ]
