# Generated by Django 6.0.1 on 2026-01-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0003_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
