# Generated by Django 5.1 on 2026-01-31 08:14

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0003_youtubevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={},
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
