# Generated by Django 6.0.1 on 2026-01-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0004_workitem_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
