# Generated by Django 5.1 on 2026-01-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0004_alter_youtubevideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
