# Generated by Django 6.0.1 on 2026-01-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0005_worksession_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='model_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='기종'),
        ),
    ]
