# Generated by Django 5.1 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manning", "0006_worksession_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksession",
            name="site",
            field=models.CharField(
                choices=[("gimpo", "gimpo"), ("incheon", "incheon")],
                default="incheon",
                max_length=20,
                verbose_name="근무지",
            ),
        ),
    ]
