# Generated by Django 5.1 on 2026-02-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0006_worksession_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeVideo',
        ),
    ]
