# Generated by Django 6.0.1 on 2026-01-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0007_add_assignment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='op',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
