# Generated by Django 5.1 on 2026-02-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manning", "0007_delete_youtubevideo"),
        ("manning", "0007_worksession_site_default_incheon"),
    ]

    operations = []
