# Generated by Django 5.1 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manning",
            "0008_merge_0007_delete_youtubevideo_0007_worksession_site_default_incheon",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmaster",
            name="site",
            field=models.CharField(
                choices=[("GIMPO", "GIMPO"), ("INCHEON", "INCHEON")],
                default="INCHEON",
                max_length=20,
                verbose_name="근무지",
            ),
        ),
    ]
