# Generated by Django 6.0.1 on 2026-01-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0008_alter_workitem_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='gibun_input',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
