# Generated by Django 6.0.1 on 2026-01-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0009_alter_workitem_gibun_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='max_mh',
            field=models.FloatField(default=9.0),
        ),
    ]
