# Generated by Django 5.1 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manning", "0010_merge_0009_alter_worksession_site_0009_taskmaster_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmaster",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
