# Generated by Django 6.0.1 on 2026-01-16 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0010_worker_max_mh'),
    ]

    operations = [
        migrations.CreateModel(
            name='GibunPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gibun', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manning.worksession')),
            ],
            options={
                'ordering': ['order', 'gibun'],
                'unique_together': {('session', 'gibun')},
            },
        ),
    ]
