# Generated by Django 6.0.1 on 2026-01-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0011_gibunpriority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gibunpriority',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='gibunpriority',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='max_mh',
        ),
        migrations.AlterField(
            model_name='gibunpriority',
            name='order',
            field=models.PositiveIntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='worker',
            name='limit_mh',
            field=models.FloatField(default=12.0),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='op',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
