# Generated by Django 6.0.1 on 2026-01-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0012_alter_gibunpriority_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='shift_type',
            field=models.CharField(choices=[('DAY', '주간 (08:00 ~ 20:00)'), ('NIGHT', '야간 (20:00 ~ 익일 08:00)')], default='DAY', max_length=10, verbose_name='근무 형태'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='name',
            field=models.CharField(max_length=100, verbose_name='세션 이름'),
        ),
    ]
