# Generated by Django 5.1 on 2026-02-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0012_alter_taskmaster_site_alter_worksession_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='site',
            field=models.CharField(choices=[('ICN-1', 'ICN-1'), ('ICN-2', 'ICN-2'), ('ICN-3', 'ICN-3'), ('GMP-1', 'GMP-1'), ('GMP-2', 'GMP-2'), ('GMP-3', 'GMP-3')], max_length=20, verbose_name='근무지'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='site',
            field=models.CharField(choices=[('ICN-1', 'ICN-1'), ('ICN-2', 'ICN-2'), ('ICN-3', 'ICN-3'), ('GMP-1', 'GMP-1'), ('GMP-2', 'GMP-2'), ('GMP-3', 'GMP-3')], max_length=20, verbose_name='근무지'),
        ),
    ]
