# Generated by Django 6.0.1 on 2026-01-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0013_worksession_shift_type_alter_worksession_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['worker', 'start_min'], name='manning_ass_worker__5c31a0_idx'),
        ),
    ]
