# Generated by Django 5.1 on 2026-02-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0013_alter_taskmaster_site_alter_worksession_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('image_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Background image',
                'verbose_name_plural': 'Background images',
            },
        ),
    ]
