# Generated by Django 6.0.1 on 2026-01-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0014_assignment_manning_ass_worker__5c31a0_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ['gibun_input', 'ordering', 'id']},
        ),
        migrations.AddField(
            model_name='workitem',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
