# Generated by Django 5.1 on 2026-02-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0014_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
