# Generated by Django 6.0.1 on 2026-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0015_alter_workitem_options_workitem_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
