# Generated by Django 5.1 on 2026-02-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manning", "0015_backgroundimage_image_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundimage",
            name="youtube_url",
            field=models.URLField(blank=True, help_text="Full YouTube URL"),
        ),
    ]
