# Generated by Django 6.0.1 on 2026-01-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0016_assignment_is_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='limit_mh',
            field=models.FloatField(default=9.0),
        ),
    ]
