# Generated by Django 5.1 on 2026-02-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0016_backgroundimage_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='site',
            field=models.CharField(choices=[('ICN-1그룹', 'ICN-1그룹'), ('ICN-2그룹', 'ICN-2그룹'), ('ICN-3그룹', 'ICN-3그룹'), ('GMP-1그룹', 'GMP-1그룹'), ('GMP-2그룹', 'GMP-2그룹'), ('GMP-3그룹', 'GMP-3그룹')], max_length=20, verbose_name='근무지'),
        ),
    ]
