# Generated by Django 5.1 on 2026-01-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0017_alter_worker_limit_mh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='op',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='work_order',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('work_item', 'worker')},
        ),
        migrations.AlterUniqueTogether(
            name='gibunpriority',
            unique_together={('session', 'gibun')},
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('session', 'name')},
        ),
        migrations.AddIndex(
            model_name='gibunpriority',
            index=models.Index(fields=['session', 'order'], name='manning_gib_session_3525d4_idx'),
        ),
    ]
