# Generated by Django 5.1 on 2026-01-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0018_alter_workitem_description_alter_workitem_op_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignment',
            name='manning_ass_worker__5c31a0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
    ]
