# Generated by Django 5.1 on 2026-01-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0019_remove_assignment_manning_ass_worker__5c31a0_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_min__isnull', True), ('start_min__isnull', True)), fields=('work_item', 'worker'), name='uniq_assignment_only_when_no_time'),
        ),
    ]
