# Generated by Django 5.1 on 2026-03-09 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0003_sessionarea_position_none'),
        ('manning', '0020_appsetting'),
    ]

    operations = [
    ]
