# Generated by Django 5.1 on 2026-01-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0020_assignment_uniq_assignment_only_when_no_time'),
    ]

    operations = [
    ]
