# Generated by Django 5.1 on 2026-03-09 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0021_merge_0003_sessionarea_position_none_0020_appsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50)),
                ('hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['worker_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('LEFT', 'LEFT SIDE'), ('RIGHT', 'RIGHT SIDE'), ('NONE', 'N/A')], default='LEFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='uniq_assignment_only_when_no_time',
        ),
        migrations.AddField(
            model_name='worksession',
            name='aircraft_reg',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='worksession',
            name='block_check',
            field=models.CharField(choices=[('1A', '1A Block Check'), ('2A', '2A Block Check'), ('3A', '3A Check Block'), ('4A', '4A Block Check')], default='1A', max_length=10),
        ),
        migrations.AddField(
            model_name='worksession',
            name='work_package_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='shift_type',
            field=models.CharField(choices=[('1', '1 Shift'), ('2', '2 Shift'), ('3', '3 Shift'), ('4', '4 Shift')], default='1', max_length=10, verbose_name='근무 형태'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='site',
            field=models.CharField(blank=True, choices=[('ICN-1그룹', 'ICN-1그룹'), ('ICN-2그룹', 'ICN-2그룹'), ('ICN-3그룹', 'ICN-3그룹'), ('GMP-1그룹', 'GMP-1그룹'), ('GMP-2그룹', 'GMP-2그룹'), ('GMP-3그룹', 'GMP-3그룹')], default='', max_length=20, verbose_name='근무지'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_min__isnull', True), ('start_min__isnull', True)), fields=('work_item', 'worker'), name='manning_uniq_assignment_no_time'),
        ),
        migrations.AddField(
            model_name='sessionarea',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='manning.worksession'),
        ),
        migrations.AddField(
            model_name='manning',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manning_set', to='manning.sessionarea'),
        ),
        migrations.AlterUniqueTogether(
            name='manning',
            unique_together={('area', 'worker_name')},
        ),
    ]
