# Generated by Django 5.1 on 2026-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manning", "0022_manning_sessionarea_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppSetting",
        ),
        migrations.DeleteModel(
            name="BackgroundImage",
        ),
        migrations.DeleteModel(
            name="FeaturedVideo",
        ),
        migrations.AlterField(
            model_name="worksession",
            name="block_check",
            field=models.CharField(
                choices=[
                    ("1A", "1A Block Check"),
                    ("2A", "2A Block Check"),
                    ("3A", "3A Block Check"),
                    ("4A", "4A Block Check"),
                ],
                default="1A",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="worksession",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("1", "1_Shift"),
                    ("2", "2_Shift"),
                    ("3", "3_Shift"),
                    ("4", "4_Shift"),
                ],
                default="1",
                max_length=10,
                verbose_name="근무 형태",
            ),
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="GibunPriority",
        ),
        migrations.DeleteModel(
            name="GibunTeam",
        ),
        migrations.DeleteModel(
            name="TaskMaster",
        ),
        migrations.DeleteModel(
            name="Worker",
        ),
        migrations.DeleteModel(
            name="WorkItem",
        ),
    ]
