# Generated by Django 5.1 on 2026-03-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0027_sessionarea_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionarea',
            options={'ordering': ['position', 'ordering', 'id']},
        ),
    ]
