# Generated by Django 5.1 on 2026-03-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0028_alter_sessionarea_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdirectory',
            name='site',
            field=models.CharField(max_length=20, verbose_name='근무지'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='site',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='근무지'),
        ),
    ]
