# Generated by Django 5.1 on 2026-04-03 08:42

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_site_directory_to_session(apps, schema_editor):
    WorkerDirectory = apps.get_model("manning", "WorkerDirectory")
    WorkSession = apps.get_model("manning", "WorkSession")

    sites = (
        WorkerDirectory.objects.exclude(site="")
        .values_list("site", flat=True)
        .distinct()
    )

    for site in sites:
        target_session = (
            WorkSession.objects.filter(site=site, is_active=True)
            .order_by("-created_at", "-id")
            .first()
        )
        if not target_session:
            target_session = (
                WorkSession.objects.filter(site=site)
                .order_by("-created_at", "-id")
                .first()
            )
        if not target_session:
            continue

        WorkerDirectory.objects.filter(site=site).update(session=target_session)


class Migration(migrations.Migration):

    dependencies = [
        ("manning", "0029_alter_workerdirectory_site_alter_worksession_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerdirectory",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker_directories",
                to="manning.worksession",
                verbose_name="세션",
            ),
        ),
        migrations.RunPython(
            copy_legacy_site_directory_to_session,
            migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name="workerdirectory",
            unique_together={("session", "name")},
        ),
        migrations.RemoveField(
            model_name="workerdirectory",
            name="site",
        ),
    ]
