# Generated by Django 5.1 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manning", "0030_alter_workerdirectory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksession",
            name="site",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="근무지"
            ),
        ),
    ]
