# Generated by Django 5.1 on 2026-04-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manning', '0031_alter_worksession_site_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='manning',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
