# Generated by Django 5.1 on 2026-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manning", "0033_worksession_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksession",
            name="important_process",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="worksession",
            name="morning_tool",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="worksession",
            name="morning_material",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="worksession",
            name="morning_bench",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="worksession",
            name="morning_towing",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="worksession",
            name="afternoon_cleanup",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="worksession",
            name="afternoon_card",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="worksession",
            name="afternoon_towing",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="worksession",
            name="special_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
